apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: goapps-production
resources:
- ../../base
patches:
- path: patches/replicas.yaml
- path: patches/resources.yaml
- path: patches/ingress-host.yaml
images:
- name: ghcr.io/mutugading/goapps-frontend
  newTag: sha-7e3bcd53fce2c9c9231aefc7d29f62880118efe4
