apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: goapps-staging

resources:
  - ../../base

patches:
  - path: patches/replicas.yaml
  - path: patches/resources.yaml
  - path: patches/ingress-host.yaml
  - path: patches/env-cors.yaml
  - path: patches/env-storage.yaml

images:
  - name: ghcr.io/mutugading/iam-service
    newTag: main  # Use main branch tag (pushed by CI)
