apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio

resources:
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: minio
  app.kubernetes.io/component: object-storage
  app.kubernetes.io/part-of: goapps
