apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: database

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - hpa.yaml
  - vpa.yaml

commonLabels:
  app.kubernetes.io/name: pgbouncer
  app.kubernetes.io/component: connection-pooler
  app.kubernetes.io/part-of: goapps
