apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: goapps-staging
resources:
- ../../base
patches:
- path: patches/replicas.yaml
- path: patches/resources.yaml
- path: patches/ingress-host.yaml
- path: patches/env-cors.yaml
images:
- name: ghcr.io/mutugading/finance-service
  newTag: "2754734"
