apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: database

resources:
  - statefulset.yaml
  - service.yaml
  - configmap.yaml
  - vpa.yaml

commonLabels:
  app.kubernetes.io/name: postgres
  app.kubernetes.io/component: database
  app.kubernetes.io/part-of: goapps
