apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: goapps-staging
resources:
- ../../base
patches:
- path: patches/replicas.yaml
- path: patches/resources.yaml
- path: patches/ingress-host.yaml
images:
- name: ghcr.io/mutugading/goapps-frontend
  newTag: dc5ec28
